"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-08-03 14:08:45.999439
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('team', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('first_aider', sa.Boolean(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_branch_id'), ['branch_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_external_id'), ['external_id'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('account_type', sa.String(length=80), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('use_case', sa.String(length=80), nullable=False),
    sa.Column('source_entity_type', sa.String(length=80), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('branch_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('team_structure', sa.Text(), nullable=True),
    sa.Column('customer_clusters', sa.Text(), nullable=True),
    sa.Column('service_portfolio', sa.Text(), nullable=True),
    sa.Column('project_types', sa.Text(), nullable=True),
    sa.Column('service_share', sa.String(length=120), nullable=True),
    sa.Column('main_problems', sa.Text(), nullable=True),
    sa.Column('management_ratings', sa.JSON(), nullable=False),
    sa.Column('next_actions', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_assessments_assessment_date'), ['assessment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_assessments_branch_id'), ['branch_id'], unique=False)

    op.create_table('compliance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(length=40), nullable=False),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('legal_basis', sa.String(length=200), nullable=False),
    sa.Column('control_type', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_if_missing', sa.Text(), nullable=True),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('recurrence', sa.String(length=40), nullable=False),
    sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_records_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_records_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('file_name', sa.String(length=240), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(length=40), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('probation_until', sa.Date(), nullable=True),
    sa.Column('residence_permit_required', sa.Boolean(), nullable=False),
    sa.Column('residence_permit_type', sa.String(length=120), nullable=True),
    sa.Column('residence_permit_valid_until', sa.Date(), nullable=True),
    sa.Column('work_permit_note', sa.Text(), nullable=True),
    sa.Column('driver_license_required', sa.Boolean(), nullable=False),
    sa.Column('driver_license_classes', sa.JSON(), nullable=False),
    sa.Column('driver_license_last_check', sa.Date(), nullable=True),
    sa.Column('driver_license_next_check', sa.Date(), nullable=True),
    sa.Column('first_aid_last_course', sa.Date(), nullable=True),
    sa.Column('first_aid_valid_until', sa.Date(), nullable=True),
    sa.Column('ipaf_last_training', sa.Date(), nullable=True),
    sa.Column('ipaf_valid_until', sa.Date(), nullable=True),
    sa.Column('general_instruction_last', sa.Date(), nullable=True),
    sa.Column('general_instruction_next', sa.Date(), nullable=True),
    sa.Column('occupational_health_required', sa.Boolean(), nullable=False),
    sa.Column('occupational_health_last', sa.Date(), nullable=True),
    sa.Column('occupational_health_next', sa.Date(), nullable=True),
    sa.Column('ppe_issued_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('development_goals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('source_type', sa.String(length=80), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('vehicle_type', sa.String(length=80), nullable=True),
    sa.Column('vin', sa.String(length=80), nullable=True),
    sa.Column('first_registration', sa.Date(), nullable=True),
    sa.Column('ownership_type', sa.String(length=80), nullable=True),
    sa.Column('assigned_employee_id', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('hu_due_date', sa.Date(), nullable=True),
    sa.Column('uvv_last_check', sa.Date(), nullable=True),
    sa.Column('uvv_next_check', sa.Date(), nullable=True),
    sa.Column('service_due_date', sa.Date(), nullable=True),
    sa.Column('tire_type', sa.String(length=40), nullable=True),
    sa.Column('tire_change_due_date', sa.Date(), nullable=True),
    sa.Column('insurance_valid_until', sa.Date(), nullable=True),
    sa.Column('fuel_card_number', sa.String(length=120), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_branch_id'), ['branch_id'], unique=False)

    op.create_table('compliance_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compliance_record_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_record_id'], ['compliance_records.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_actions_compliance_record_id'), ['compliance_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_actions_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_actions_status'), ['status'], unique=False)

    op.create_table('employee_qualifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('qualification_type', sa.String(length=80), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_qualifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_qualifications_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_qualifications_valid_until'), ['valid_until'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('offer_status', sa.String(length=80), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_volume', sa.Float(), nullable=False),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('strategic_relevance', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('risk_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('sla_response_hours', sa.Integer(), nullable=True),
    sa.Column('next_maintenance_at', sa.Date(), nullable=True),
    sa.Column('upsell_hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_contracts_next_maintenance_at'), ['next_maintenance_at'], unique=False)

    op.create_table('compliance_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('compliance_record_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=240), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('evidence_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('linked_employee_id', sa.String(), nullable=True),
    sa.Column('linked_project_id', sa.String(), nullable=True),
    sa.Column('linked_equipment_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_record_id'], ['compliance_records.id'], ),
    sa.ForeignKeyConstraint(['linked_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['linked_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_evidence_compliance_record_id'), ['compliance_record_id'], unique=False)

    op.create_table('project_sites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('service_contract_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('scheduled_at', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('repeat_issue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_contract_id'], ['service_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['project_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_incidents_branch_id'))

    op.drop_table('incidents')
    op.drop_table('service_events')
    op.drop_table('project_sites')
    with op.batch_alter_table('compliance_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_evidence_compliance_record_id'))

    op.drop_table('compliance_evidence')
    with op.batch_alter_table('service_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_contracts_next_maintenance_at'))

    op.drop_table('service_contracts')
    op.drop_table('projects')
    op.drop_table('opportunities')
    with op.batch_alter_table('employee_qualifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_qualifications_valid_until'))
        batch_op.drop_index(batch_op.f('ix_employee_qualifications_employee_id'))

    op.drop_table('employee_qualifications')
    with op.batch_alter_table('compliance_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_actions_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_actions_due_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_actions_compliance_record_id'))

    op.drop_table('compliance_actions')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_branch_id'))

    op.drop_table('vehicles')
    op.drop_table('tasks')
    op.drop_table('employee_reviews')
    op.drop_table('employee_profiles')
    op.drop_table('documents')
    with op.batch_alter_table('compliance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_records_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_due_date'))
        batch_op.drop_index(batch_op.f('ix_compliance_records_branch_id'))

    op.drop_table('compliance_records')
    with op.batch_alter_table('branch_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branch_assessments_branch_id'))
        batch_op.drop_index(batch_op.f('ix_branch_assessments_assessment_date'))

    op.drop_table('branch_assessments')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    op.drop_table('agent_runs')
    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_external_id'))

    op.drop_table('users')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_branch_id'))

    op.drop_table('employees')
    op.drop_table('roles')
    op.drop_table('branches')
    # ### end Alembic commands ###
