"""sales fields and upload metadata

Revision ID: 0003_sales
Revises: 0002_auth
Create Date: 2026-08-03 14:43:38.345334
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_sales'
down_revision: Union[str, None] = '0002_auth'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # branch_id is nullable at the schema level so existing rows survive the
    # migration; the API requires it on create.
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_accounts_branch_id'), ['branch_id'], unique=False)
        batch_op.create_foreign_key('fk_accounts_branch_id_branches', 'branches', ['branch_id'], ['id'])

    with op.batch_alter_table('compliance_evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=True))

    with op.batch_alter_table('employee_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_reviews_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('project_sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_sites_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('service_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_contracts_account_id'), ['account_id'], unique=False)

    with op.batch_alter_table('service_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_events_service_contract_id'), ['service_contract_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_events_service_contract_id'))

    with op.batch_alter_table('service_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_contracts_account_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_account_id'))

    with op.batch_alter_table('project_sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_sites_project_id'))

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_account_id'))

    with op.batch_alter_table('employee_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_reviews_employee_id'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('file_size_bytes')

    with op.batch_alter_table('compliance_evidence', schema=None) as batch_op:
        batch_op.drop_column('file_size_bytes')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_branch_id_branches', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_accounts_branch_id'))
        batch_op.drop_column('notes')
        batch_op.drop_column('industry')
        batch_op.drop_column('branch_id')

    # ### end Alembic commands ###
