"""File storage for evidence and documents.

Storage paths are generated by the server. The client never supplies one, and
the stored name never derives from the uploaded filename, so a crafted name
cannot escape the uploads directory.
"""

from __future__ import annotations

import re
import shutil
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from uuid import uuid4

from fastapi import HTTPException, UploadFile, status

from .config import settings
from .domain import now_utc

# Read in chunks so a large upload never has to fit in memory at once.
CHUNK_SIZE = 1024 * 1024
_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]+")


@dataclass(frozen=True)
class StoredFile:
    storage_path: str
    file_name: str
    mime_type: str | None
    size_bytes: int


def uploads_root() -> Path:
    return Path(settings.uploads_dir).resolve()


def safe_display_name(name: str | None) -> str:
    """Normalises the original name for display; it is never used as a path."""
    candidate = unicodedata.normalize("NFKD", name or "").encode("ascii", "ignore").decode()
    candidate = _SAFE_NAME.sub("_", candidate).strip("._-")
    return candidate[:200] or "upload"


def _extension(name: str | None) -> str:
    suffix = Path(name or "").suffix.lower()
    allowed = settings.allowed_extensions
    if suffix not in allowed:
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail=f"File type '{suffix or 'unknown'}' is not accepted. Allowed: {', '.join(sorted(allowed))}",
        )
    return suffix


def store_upload(upload: UploadFile, *, category: str) -> StoredFile:
    """Writes an upload below UPLOADS_DIR and returns its metadata.

    Raises 413 when the stream exceeds UPLOAD_MAX_BYTES; the partial file is
    removed so a rejected upload leaves nothing behind.
    """
    suffix = _extension(upload.filename)
    stamp = now_utc()
    relative = Path(category) / f"{stamp:%Y}" / f"{stamp:%m}" / f"{uuid4().hex}{suffix}"
    target = uploads_root() / relative
    target.parent.mkdir(parents=True, exist_ok=True)

    size = 0
    try:
        with target.open("wb") as sink:
            while chunk := upload.file.read(CHUNK_SIZE):
                size += len(chunk)
                if size > settings.upload_max_bytes:
                    raise HTTPException(
                        status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
                        detail=f"File exceeds the limit of {settings.upload_max_bytes} bytes.",
                    )
                sink.write(chunk)
    except Exception:
        target.unlink(missing_ok=True)
        raise

    if size == 0:
        target.unlink(missing_ok=True)
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="The uploaded file is empty.")

    return StoredFile(
        storage_path=str(relative).replace("\\", "/"),
        file_name=safe_display_name(upload.filename),
        mime_type=upload.content_type,
        size_bytes=size,
    )


def resolve(storage_path: str) -> Path:
    """Maps a stored relative path back to a file, refusing anything outside the root.

    Rows written before uploads existed may hold arbitrary client-supplied
    strings, so this is validated rather than trusted.
    """
    root = uploads_root()
    candidate = (root / storage_path).resolve()
    if not candidate.is_relative_to(root):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="File not found")
    if not candidate.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="The referenced file is not present in storage.",
        )
    return candidate


def delete(storage_path: str) -> None:
    """Best-effort removal; a missing file must not block deleting the row."""
    try:
        root = uploads_root()
        candidate = (root / storage_path).resolve()
        if candidate.is_relative_to(root) and candidate.is_file():
            candidate.unlink()
    except OSError:
        pass


def disk_usage_bytes() -> int:
    root = uploads_root()
    if not root.exists():
        return 0
    return sum(item.stat().st_size for item in root.rglob("*") if item.is_file())


def clear_all() -> None:  # pragma: no cover - test helper
    root = uploads_root()
    if root.exists():
        shutil.rmtree(root)
