import React from "react";
import ReactDOM from "react-dom/client";
import { AlertTriangle, BriefcaseBusiness, CalendarClock, ClipboardCheck, FileCheck2, Gauge, NotebookPen, UserRoundCheck, Wrench } from "lucide-react";
import "./styles.css";

const API_BASE = import.meta.env.VITE_API_BASE_URL || `${window.location.protocol}//${window.location.hostname}:8000`;
const WRITE_HEADERS = { "Content-Type": "application/json", "X-User-Role": "branch-manager" };

type State = "red" | "yellow" | "green";
type Metric = { label: string; value: number; state: State };
type Reminder = { source_type: string; source_id: string; title: string; due_date: string; state: State; owner_hint?: string | null };
type Action = { id: string; compliance_record_id: string; title: string; due_date: string; priority: string; status: string; due_state: State };
type RecordItem = { id: string; title: string; category: string; status: string; priority: string; owner_user_id: string; legal_basis: string; control_type: string; due_date: string; review_date: string; risk_if_missing?: string | null; evidence_summary?: string | null; tags: string[]; due_state: State; overdue: boolean; evidence: unknown[]; actions: Action[] };
type EmployeeProfile = { id: string; employee_id: string; contract_type: string; contract_start?: string | null; contract_end?: string | null; probation_until?: string | null; residence_permit_required: boolean; residence_permit_type?: string | null; residence_permit_valid_until?: string | null; work_permit_note?: string | null; driver_license_required: boolean; driver_license_classes: string[]; driver_license_last_check?: string | null; driver_license_next_check?: string | null; first_aid_last_course?: string | null; first_aid_valid_until?: string | null; ipaf_last_training?: string | null; ipaf_valid_until?: string | null; general_instruction_last?: string | null; general_instruction_next?: string | null; occupational_health_required: boolean; occupational_health_last?: string | null; occupational_health_next?: string | null; ppe_issued_at?: string | null; notes?: string | null };
type Employee = { id: string; branch_id: string; full_name: string; role: string; team?: string | null; start_date?: string | null; first_aider: boolean; skills: string[]; profile?: EmployeeProfile | null };
type Vehicle = { id: string; branch_id: string; license_plate: string; brand?: string | null; model?: string | null; vehicle_type?: string | null; vin?: string | null; first_registration?: string | null; ownership_type?: string | null; assigned_employee_id?: string | null; mileage?: number | null; hu_due_date?: string | null; uvv_last_check?: string | null; uvv_next_check?: string | null; service_due_date?: string | null; tire_type?: string | null; tire_change_due_date?: string | null; insurance_valid_until?: string | null; fuel_card_number?: string | null; equipment: string[]; notes?: string | null };
type Assessment = { id: string; branch_id: string; title: string; assessment_date: string; team_structure?: string | null; customer_clusters?: string | null; service_portfolio?: string | null; project_types?: string | null; service_share?: string | null; main_problems?: string | null; management_ratings: Record<string, string>; next_actions: { title?: string }[]; notes?: string | null };
type Cockpit = { metrics: Metric[]; reminders: Reminder[]; overdue_compliance: RecordItem[]; due_soon_compliance: RecordItem[]; open_actions: Action[]; pipeline_value: number; service_due_count: number; vehicle_due_count: number; employee_due_count: number };
type Bootstrap = { branches: { id: string; name: string }[]; users: { id: string; display_name: string }[] };

function formatDate(value?: string | null) {
  if (!value) return "-";
  return new Intl.DateTimeFormat("de-DE").format(new Date(value));
}
function splitCsv(value: FormDataEntryValue | null) {
  return String(value || "").split(",").map((item) => item.trim()).filter(Boolean);
}
function emptyToNull(value: FormDataEntryValue | null) {
  const text = String(value || "").trim();
  return text ? text : null;
}
function Badge({ state, children }: { state: State | string; children: React.ReactNode }) {
  return <span className={`badge ${state}`}>{children}</span>;
}

function useOpsData() {
  const [cockpit, setCockpit] = React.useState<Cockpit | null>(null);
  const [assessments, setAssessments] = React.useState<Assessment[]>([]);
  const [records, setRecords] = React.useState<RecordItem[]>([]);
  const [actions, setActions] = React.useState<Action[]>([]);
  const [employees, setEmployees] = React.useState<Employee[]>([]);
  const [vehicles, setVehicles] = React.useState<Vehicle[]>([]);
  const [reminders, setReminders] = React.useState<Reminder[]>([]);
  const [bootstrap, setBootstrap] = React.useState<Bootstrap>({ branches: [], users: [] });
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  const load = React.useCallback(async () => {
    try {
      setLoading(true);
      const [cockpitRes, assessmentRes, recordsRes, actionsRes, employeesRes, vehiclesRes, remindersRes, bootstrapRes] = await Promise.all([
        fetch(`${API_BASE}/api/cockpit`), fetch(`${API_BASE}/api/branch-assessments`), fetch(`${API_BASE}/api/compliance-records`), fetch(`${API_BASE}/api/actions`), fetch(`${API_BASE}/api/employees`), fetch(`${API_BASE}/api/vehicles`), fetch(`${API_BASE}/api/reminders`), fetch(`${API_BASE}/api/bootstrap`),
      ]);
      for (const response of [cockpitRes, assessmentRes, recordsRes, actionsRes, employeesRes, vehiclesRes, remindersRes, bootstrapRes]) if (!response.ok) throw new Error(`API ${response.status}`);
      setCockpit(await cockpitRes.json()); setAssessments(await assessmentRes.json()); setRecords(await recordsRes.json()); setActions(await actionsRes.json()); setEmployees(await employeesRes.json()); setVehicles(await vehiclesRes.json()); setReminders(await remindersRes.json()); setBootstrap(await bootstrapRes.json()); setError(null);
    } catch (err) { setError(err instanceof Error ? err.message : "Unbekannter Fehler"); } finally { setLoading(false); }
  }, []);
  React.useEffect(() => { load(); }, [load]);
  return { cockpit, assessments, records, actions, employees, vehicles, reminders, bootstrap, loading, error, reload: load };
}

function App() {
  const data = useOpsData();
  const [view, setView] = React.useState("cockpit");
  const titleMap: Record<string, string> = { cockpit: "Leitercockpit", assessment: "Bestandsaufnahme", employees: "Mitarbeiter", vehicles: "Fahrzeuge", compliance: "Compliance", sales: "Vertrieb" };
  return <div className="shell"><aside className="sidebar"><div className="brand"><Gauge size={22} /><div><strong>Remscheid Ops</strong><span>Niederlassungsleitung</span></div></div><nav>{[
    ["cockpit", Gauge, "Cockpit"], ["assessment", NotebookPen, "Bestandsaufnahme"], ["employees", UserRoundCheck, "Mitarbeiter"], ["vehicles", Wrench, "Fahrzeuge"], ["compliance", ClipboardCheck, "Compliance"], ["sales", BriefcaseBusiness, "Vertrieb"],
  ].map(([key, Icon, label]) => <button key={String(key)} className={view === key ? "active" : ""} onClick={() => setView(String(key))}>{React.createElement(Icon as any, { size: 18 })}{String(label)}</button>)}</nav></aside><main><header className="topbar"><div><h1>{titleMap[view]}</h1><p>Objekte, Fristen und Erinnerungen fuer die Fuehrung der Niederlassung. Persistenz: lokale SQLite-Testdatenbank.</p></div><button className="iconButton" title="Daten neu laden" onClick={data.reload}><FileCheck2 size={18} /></button></header>{data.loading && <div className="notice">Daten werden geladen...</div>}{data.error && <div className="notice danger">Backend nicht erreichbar: {data.error}</div>}{!data.loading && !data.error && data.cockpit && <>{view === "cockpit" && <CockpitView {...data} cockpit={data.cockpit} />}{view === "assessment" && <AssessmentView assessments={data.assessments} bootstrap={data.bootstrap} onSaved={data.reload} />}{view === "employees" && <EmployeeView employees={data.employees} bootstrap={data.bootstrap} onReload={data.reload} />}{view === "vehicles" && <VehicleView vehicles={data.vehicles} employees={data.employees} bootstrap={data.bootstrap} onReload={data.reload} />}{view === "compliance" && <ComplianceView records={data.records} actions={data.actions} bootstrap={data.bootstrap} onReload={data.reload} />}{view === "sales" && <Placeholder title="Vertrieb / Pipeline" icon={<BriefcaseBusiness />} lines={["Noch keine Vertriebsdaten erfasst.", "Accounts und Opportunities bleiben eigenstaendige Eingaben, kein Dashboard-Import."]} />}</>}</main></div>;
}

function CockpitView({ cockpit, assessments, reminders, employees, vehicles }: { cockpit: Cockpit; assessments: Assessment[]; reminders: Reminder[]; employees: Employee[]; vehicles: Vehicle[] }) {
  return <section className="stack"><div className="metrics">{cockpit.metrics.map((metric) => <div className="metric" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><Badge state={metric.state}>{metric.state}</Badge></div>)}</div><div className="grid two"><Panel title="Akute Erinnerungen" icon={<CalendarClock size={18} />}><ReminderList reminders={reminders} /></Panel><Panel title="Mitarbeiterstatus" icon={<UserRoundCheck size={18} />}><p>{employees.length} Mitarbeiter erfasst.</p><ul className="list">{employees.map((employee) => <li key={employee.id}><strong>{employee.full_name}</strong><span>{employee.role} / {employee.profile ? "Pflichtenprofil erfasst" : "Pflichtenprofil offen"}</span></li>)}</ul></Panel><Panel title="Fuhrparkstatus" icon={<Wrench size={18} />}><p>{vehicles.length} Fahrzeuge erfasst.</p><ul className="list">{vehicles.map((vehicle) => <li key={vehicle.id}><strong>{vehicle.license_plate}</strong><span>{vehicle.brand || "-"} {vehicle.model || ""} / Reifenwechsel {formatDate(vehicle.tire_change_due_date)}</span></li>)}</ul></Panel><Panel title="Letzte Bestandsaufnahme" icon={<NotebookPen size={18} />}>{assessments[0] ? <AssessmentSummary assessment={assessments[0]} /> : <div className="empty">Noch keine Bestandsaufnahme erfasst.</div>}</Panel></div></section>;
}
function ReminderList({ reminders }: { reminders: Reminder[] }) {
  if (!reminders.length) return <div className="empty">Keine faelligen Erinnerungen in den naechsten 60 Tagen.</div>;
  return <table><thead><tr><th>Status</th><th>Thema</th><th>Faellig</th></tr></thead><tbody>{reminders.map((item) => <tr key={`${item.source_type}-${item.source_id}-${item.title}`}><td><Badge state={item.state}>{item.state}</Badge></td><td><strong>{item.title}</strong><span>{item.source_type}</span></td><td>{formatDate(item.due_date)}</td></tr>)}</tbody></table>;
}

function AssessmentView({ assessments, bootstrap, onSaved }: { assessments: Assessment[]; bootstrap: Bootstrap; onSaved: () => void }) {
  const latest = assessments[0];
  return <div className="grid detailLayout"><section className="stack"><AssessmentForm bootstrap={bootstrap} onSaved={onSaved} />{assessments.length > 0 && <Panel title="Erfasste Bestandsaufnahmen" icon={<NotebookPen size={18} />}><AssessmentTable assessments={assessments} /></Panel>}</section><aside className="detail"><div className="detailHeader"><Badge state={latest ? "green" : "yellow"}>{latest ? "erfasst" : "offen"}</Badge><h2>{latest?.title || "Noch keine Bestandsaufnahme"}</h2><p>{latest ? formatDate(latest.assessment_date) : ""}</p></div>{latest ? <AssessmentSummary assessment={latest} /> : <div className="empty">Bitte die erste Bestandsaufnahme erfassen.</div>}</aside></div>;
}
function AssessmentForm({ bootstrap, onSaved }: { bootstrap: Bootstrap; onSaved: () => void }) {
  const branchId = bootstrap.branches[0]?.id || "branch-remscheid"; const userId = bootstrap.users[0]?.id || "user-branch-manager";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const next_actions = String(data.get("next_actions_text") || "").split(/\r?\n/).map((line) => line.trim()).filter(Boolean).map((title) => ({ title })); const payload = { branch_id: branchId, created_by: userId, title: data.get("title"), assessment_date: data.get("assessment_date"), team_structure: data.get("team_structure"), customer_clusters: data.get("customer_clusters"), service_portfolio: data.get("service_portfolio"), project_types: data.get("project_types"), service_share: data.get("service_share"), main_problems: data.get("main_problems"), notes: data.get("notes"), next_actions, management_ratings: { compliance: data.get("rating_compliance"), personal: data.get("rating_personal"), service: data.get("rating_service"), sales: data.get("rating_sales"), operations: data.get("rating_operations") } }; await fetch(`${API_BASE}/api/branch-assessments`, { method: "POST", headers: WRITE_HEADERS, body: JSON.stringify(payload) }); form.reset(); onSaved(); }
  return <form className="form" onSubmit={submit}><h2>Bestandsaufnahme erfassen</h2><div className="formGrid"><input name="title" placeholder="Titel" defaultValue="Bestandsaufnahme Remscheid" required /><label>Datum<input name="assessment_date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label></div><textarea name="team_structure" placeholder="Teamstruktur, Rollen, Verantwortliche" /><textarea name="customer_clusters" placeholder="Kundencluster und wichtige Accounts" /><textarea name="service_portfolio" placeholder="Leistungsportfolio" /><textarea name="project_types" placeholder="Projektarten und typische Baustellen" /><input name="service_share" placeholder="Service-/Wartungsanteil" /><textarea name="main_problems" placeholder="Aktuelle Hauptprobleme" /><div className="formGrid">{["compliance", "personal", "service", "sales", "operations"].map((key) => <label key={key}>{key}<select name={`rating_${key}`} defaultValue="yellow"><option value="green">gruen</option><option value="yellow">gelb</option><option value="red">rot</option></select></label>)}</div><textarea name="next_actions_text" placeholder="Massnahmen, eine pro Zeile" /><textarea name="notes" placeholder="Bestandsaufnahme-Text / erzeugte Notizen" /><button>Bestandsaufnahme speichern</button></form>;
}
function AssessmentTable({ assessments }: { assessments: Assessment[] }) { return <table><thead><tr><th>Datum</th><th>Titel</th><th>Personal</th></tr></thead><tbody>{assessments.map((item) => <tr key={item.id}><td>{formatDate(item.assessment_date)}</td><td><strong>{item.title}</strong><span>{item.main_problems || "-"}</span></td><td><Badge state={item.management_ratings.personal || "yellow"}>{item.management_ratings.personal || "offen"}</Badge></td></tr>)}</tbody></table>; }
function AssessmentSummary({ assessment }: { assessment: Assessment }) { return <div className="stack"><dl><dt>Team</dt><dd>{assessment.team_structure || "-"}</dd><dt>Kunden</dt><dd>{assessment.customer_clusters || "-"}</dd><dt>Portfolio</dt><dd>{assessment.service_portfolio || "-"}</dd><dt>Probleme</dt><dd>{assessment.main_problems || "-"}</dd></dl><h3>Ampeln</h3><div className="chips">{Object.entries(assessment.management_ratings || {}).map(([key, value]) => <span key={key}>{key}: {value}</span>)}</div></div>; }

function EmployeeView({ employees, bootstrap, onReload }: { employees: Employee[]; bootstrap: Bootstrap; onReload: () => void }) {
  return <section className="stack"><EmployeeForm bootstrap={bootstrap} onSaved={onReload} /><div className="grid two">{employees.map((employee) => <Panel key={employee.id} title={employee.full_name} icon={<UserRoundCheck size={18} />}><EmployeeSummary employee={employee} /></Panel>)}</div></section>;
}
function EmployeeSummary({ employee }: { employee: Employee }) {
  const p = employee.profile;
  return <div className="stack"><div className="person"><strong>{employee.role}</strong><span>{employee.team || "-"} / Start {formatDate(employee.start_date)}</span></div><div className="chips">{employee.skills.map((skill) => <span key={skill}>{skill}</span>)}</div>{p ? <dl><dt>Vertrag</dt><dd>{p.contract_type} bis {formatDate(p.contract_end)}</dd><dt>Aufenthalt</dt><dd>{p.residence_permit_required ? `${p.residence_permit_type || "pflichtig"} bis ${formatDate(p.residence_permit_valid_until)}` : "nicht erfasst/pflichtig"}</dd><dt>Fuehrerschein</dt><dd>{p.driver_license_required ? `${p.driver_license_classes.join(", ")} / Kontrolle ${formatDate(p.driver_license_next_check)}` : "nicht benoetigt"}</dd><dt>EH / IPAF</dt><dd>{formatDate(p.first_aid_valid_until)} / {formatDate(p.ipaf_valid_until)}</dd><dt>Unterweisung</dt><dd>{formatDate(p.general_instruction_next)}</dd><dt>Vorsorge</dt><dd>{formatDate(p.occupational_health_next)}</dd></dl> : <div className="empty">Pflichtenprofil noch nicht erfasst.</div>}</div>;
}
function EmployeeForm({ bootstrap, onSaved }: { bootstrap: Bootstrap; onSaved: () => void }) {
  const branchId = bootstrap.branches[0]?.id || "branch-remscheid";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const skills = splitCsv(data.get("skills")); const employeeRes = await fetch(`${API_BASE}/api/employees`, { method: "POST", headers: WRITE_HEADERS, body: JSON.stringify({ branch_id: branchId, full_name: data.get("full_name"), role: data.get("role"), team: data.get("team"), start_date: emptyToNull(data.get("start_date")), first_aider: data.get("first_aider") === "on", skills }) }); const employee = await employeeRes.json(); const profile = { employee_id: employee.id, contract_type: data.get("contract_type"), contract_start: emptyToNull(data.get("contract_start")), contract_end: emptyToNull(data.get("contract_end")), probation_until: emptyToNull(data.get("probation_until")), residence_permit_required: data.get("residence_permit_required") === "on", residence_permit_type: emptyToNull(data.get("residence_permit_type")), residence_permit_valid_until: emptyToNull(data.get("residence_permit_valid_until")), work_permit_note: emptyToNull(data.get("work_permit_note")), driver_license_required: data.get("driver_license_required") === "on", driver_license_classes: splitCsv(data.get("driver_license_classes")), driver_license_last_check: emptyToNull(data.get("driver_license_last_check")), driver_license_next_check: emptyToNull(data.get("driver_license_next_check")), first_aid_last_course: emptyToNull(data.get("first_aid_last_course")), first_aid_valid_until: emptyToNull(data.get("first_aid_valid_until")), ipaf_last_training: emptyToNull(data.get("ipaf_last_training")), ipaf_valid_until: emptyToNull(data.get("ipaf_valid_until")), general_instruction_last: emptyToNull(data.get("general_instruction_last")), general_instruction_next: emptyToNull(data.get("general_instruction_next")), occupational_health_required: data.get("occupational_health_required") === "on", occupational_health_last: emptyToNull(data.get("occupational_health_last")), occupational_health_next: emptyToNull(data.get("occupational_health_next")), ppe_issued_at: emptyToNull(data.get("ppe_issued_at")), notes: emptyToNull(data.get("notes")) }; await fetch(`${API_BASE}/api/employee-profiles`, { method: "POST", headers: WRITE_HEADERS, body: JSON.stringify(profile) }); form.reset(); onSaved(); }
  return <form className="form" onSubmit={submit}><h2>Mitarbeiter + Pflichtenprofil erfassen</h2><div className="formGrid"><input name="full_name" placeholder="Name" required /><input name="role" placeholder="Rolle" required /><input name="team" placeholder="Team" /><label>Eintritt<input name="start_date" type="date" /></label><input name="skills" placeholder="Skills, kommagetrennt" /><label>Vertrag<select name="contract_type" defaultValue="unbefristet"><option value="unbefristet">unbefristet</option><option value="befristet">befristet</option><option value="probezeit/praktikum">Probezeit/Praktikum</option></select></label><label>Vertragsbeginn<input name="contract_start" type="date" /></label><label>Befristet bis<input name="contract_end" type="date" /></label><label>Probezeit bis<input name="probation_until" type="date" /></label></div><div className="formGrid"><label><input name="residence_permit_required" type="checkbox" /> Aufenthalt/Arbeitserlaubnis relevant</label><input name="residence_permit_type" placeholder="Art Aufenthaltstitel" /><label>Aufenthalt gueltig bis<input name="residence_permit_valid_until" type="date" /></label><input name="work_permit_note" placeholder="Arbeitsgenehmigung/Notiz" /></div><div className="formGrid"><label><input name="driver_license_required" type="checkbox" /> Fuehrerschein erforderlich</label><input name="driver_license_classes" placeholder="Klassen, z. B. B, BE" /><label>Letzte Kontrolle<input name="driver_license_last_check" type="date" /></label><label>Naechste Kontrolle<input name="driver_license_next_check" type="date" /></label></div><div className="formGrid"><label>Letzter EH-Kurs<input name="first_aid_last_course" type="date" /></label><label>EH gueltig bis<input name="first_aid_valid_until" type="date" /></label><label>Letzte IPAF<input name="ipaf_last_training" type="date" /></label><label>IPAF gueltig bis<input name="ipaf_valid_until" type="date" /></label><label>Letzte Unterweisung<input name="general_instruction_last" type="date" /></label><label>Naechste Unterweisung<input name="general_instruction_next" type="date" /></label><label><input name="occupational_health_required" type="checkbox" /> Arbeitsmedizin relevant</label><label>Naechste Vorsorge<input name="occupational_health_next" type="date" /></label><label>PSA ausgegeben<input name="ppe_issued_at" type="date" /></label></div><textarea name="notes" placeholder="Weitere Pflichten, Dokumente, Besonderheiten" /><button>Mitarbeiter speichern</button></form>;
}

function VehicleView({ vehicles, employees, bootstrap, onReload }: { vehicles: Vehicle[]; employees: Employee[]; bootstrap: Bootstrap; onReload: () => void }) {
  return <section className="stack"><VehicleForm employees={employees} bootstrap={bootstrap} onSaved={onReload} /><div className="grid two">{vehicles.map((vehicle) => <Panel key={vehicle.id} title={vehicle.license_plate} icon={<Wrench size={18} />}><dl><dt>Fahrzeug</dt><dd>{vehicle.brand || "-"} {vehicle.model || ""} / {vehicle.vehicle_type || "-"}</dd><dt>HU</dt><dd>{formatDate(vehicle.hu_due_date)}</dd><dt>UVV</dt><dd>{formatDate(vehicle.uvv_next_check)}</dd><dt>Service</dt><dd>{formatDate(vehicle.service_due_date)}</dd><dt>Reifen</dt><dd>{vehicle.tire_type || "-"} / Wechsel {formatDate(vehicle.tire_change_due_date)}</dd><dt>Versicherung</dt><dd>{formatDate(vehicle.insurance_valid_until)}</dd></dl><div className="chips">{vehicle.equipment.map((item) => <span key={item}>{item}</span>)}</div></Panel>)}</div></section>;
}
function VehicleForm({ employees, bootstrap, onSaved }: { employees: Employee[]; bootstrap: Bootstrap; onSaved: () => void }) {
  const branchId = bootstrap.branches[0]?.id || "branch-remscheid";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const payload = { branch_id: branchId, license_plate: data.get("license_plate"), brand: emptyToNull(data.get("brand")), model: emptyToNull(data.get("model")), vehicle_type: emptyToNull(data.get("vehicle_type")), vin: emptyToNull(data.get("vin")), first_registration: emptyToNull(data.get("first_registration")), ownership_type: emptyToNull(data.get("ownership_type")), assigned_employee_id: emptyToNull(data.get("assigned_employee_id")), mileage: data.get("mileage") ? Number(data.get("mileage")) : null, hu_due_date: emptyToNull(data.get("hu_due_date")), uvv_last_check: emptyToNull(data.get("uvv_last_check")), uvv_next_check: emptyToNull(data.get("uvv_next_check")), service_due_date: emptyToNull(data.get("service_due_date")), tire_type: emptyToNull(data.get("tire_type")), tire_change_due_date: emptyToNull(data.get("tire_change_due_date")), insurance_valid_until: emptyToNull(data.get("insurance_valid_until")), fuel_card_number: emptyToNull(data.get("fuel_card_number")), equipment: splitCsv(data.get("equipment")), notes: emptyToNull(data.get("notes")) }; await fetch(`${API_BASE}/api/vehicles`, { method: "POST", headers: WRITE_HEADERS, body: JSON.stringify(payload) }); form.reset(); onSaved(); }
  return <form className="form" onSubmit={submit}><h2>Fahrzeug erfassen</h2><div className="formGrid"><input name="license_plate" placeholder="Kennzeichen" required /><input name="brand" placeholder="Marke" /><input name="model" placeholder="Modell / Typ" /><input name="vehicle_type" placeholder="Art, z. B. Transporter" /><input name="vin" placeholder="FIN/VIN" /><label>Erstzulassung<input name="first_registration" type="date" /></label><select name="ownership_type" defaultValue=""><option value="">Eigentum/Leasing</option><option value="Eigentum">Eigentum</option><option value="Leasing">Leasing</option><option value="Miete">Miete</option></select><select name="assigned_employee_id" defaultValue=""><option value="">Zugeordnet an</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.full_name}</option>)}</select><input name="mileage" type="number" placeholder="Kilometerstand" /></div><div className="formGrid"><label>HU faellig<input name="hu_due_date" type="date" /></label><label>Letzte UVV<input name="uvv_last_check" type="date" /></label><label>Naechste UVV<input name="uvv_next_check" type="date" /></label><label>Service faellig<input name="service_due_date" type="date" /></label><select name="tire_type" defaultValue=""><option value="">Reifen</option><option>Sommer</option><option>Winter</option><option>Ganzjahr</option></select><label>Reifenwechsel<input name="tire_change_due_date" type="date" /></label><label>Versicherung bis<input name="insurance_valid_until" type="date" /></label><input name="fuel_card_number" placeholder="Tankkarte" /></div><input name="equipment" placeholder="Ausstattung, z. B. Leiter, Feuerloescher, Verbandkasten" /><textarea name="notes" placeholder="Notizen / Besonderheiten" /><button>Fahrzeug speichern</button></form>;
}

function ComplianceView({ records, actions, bootstrap, onReload }: { records: RecordItem[]; actions: Action[]; bootstrap: Bootstrap; onReload: () => void }) {
  return <section className="stack"><CreateRecordForm bootstrap={bootstrap} onCreated={onReload} /><Panel title="Compliance-Records" icon={<ClipboardCheck size={18} />}><RecordTable records={records} /></Panel><Panel title="Massnahmen" icon={<AlertTriangle size={18} />}><ActionTable actions={actions} records={records} /></Panel></section>;
}
function RecordTable({ records }: { records: RecordItem[] }) { if (!records.length) return <div className="empty">Keine Eintraege erfasst.</div>; return <table><thead><tr><th>Status</th><th>Titel</th><th>Faellig</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><Badge state={record.due_state}>{record.priority}</Badge></td><td><strong>{record.title}</strong><span>{record.category}</span></td><td>{formatDate(record.due_date)}</td></tr>)}</tbody></table>; }
function CreateRecordForm({ bootstrap, onCreated }: { bootstrap: Bootstrap; onCreated: () => void }) { const branchId = bootstrap.branches[0]?.id || "branch-remscheid"; const ownerId = bootstrap.users[0]?.id || "user-branch-manager"; async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form).entries()); await fetch(`${API_BASE}/api/compliance-records`, { method: "POST", headers: WRITE_HEADERS, body: JSON.stringify({ ...payload, branch_id: branchId, owner_user_id: ownerId, tags: [], scope_type: "branch", recurrence: "yearly" }) }); form.reset(); onCreated(); } return <form className="form" onSubmit={submit}><h2>Compliance-Thema erfassen</h2><input name="title" placeholder="Titel" required /><div className="formGrid"><select name="category" defaultValue="training_instruction"><option value="training_instruction">Unterweisung</option><option value="risk_assessment">Gefaehrdungsbeurteilung</option><option value="tools_and_equipment_inspection">DGUV / Arbeitsmittel</option><option value="first_aid">Erste Hilfe</option></select><select name="priority" defaultValue="high"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><select name="status" defaultValue="open"><option>open</option><option>in_progress</option><option>compliant</option><option>non_compliant</option></select><select name="control_type" defaultValue="training"><option>document</option><option>training</option><option>inspection</option><option>medical</option><option>process</option><option>incident</option><option>approval</option></select></div><input name="legal_basis" placeholder="Rechtsgrundlage" required /><div className="formGrid"><label>Faellig<input name="due_date" type="date" required /></label><label>Review<input name="review_date" type="date" required /></label></div><textarea name="risk_if_missing" placeholder="Risiko bei fehlendem Nachweis" /><button>Speichern</button></form>; }
function ActionTable({ actions, records }: { actions: Action[]; records: RecordItem[] }) { if (!actions.length) return <div className="empty">Keine offenen Massnahmen erfasst.</div>; return <table><thead><tr><th>Status</th><th>Massnahme</th><th>Record</th><th>Faellig</th></tr></thead><tbody>{actions.map((action) => <tr key={action.id}><td><Badge state={action.due_state}>{action.status}</Badge></td><td><strong>{action.title}</strong><span>{action.priority}</span></td><td>{records.find((record) => record.id === action.compliance_record_id)?.title || action.compliance_record_id}</td><td>{formatDate(action.due_date)}</td></tr>)}</tbody></table>; }
function Panel({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="panel"><div className="panelTitle">{icon}<h2>{title}</h2></div>{children}</section>; }
function Placeholder({ title, icon, lines }: { title: string; icon: React.ReactNode; lines: string[] }) { return <Panel title={title} icon={icon}>{lines.map((line) => <p key={line}>{line}</p>)}</Panel>; }

ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
